labels: ["bug"]
body:
  - type: input
    id: parent
    attributes:
      label: "관련된 Story/Task/Epic"
      description: "버그가 발생한 상위 이슈 번호를 입력하세요 (Jira 연동)"
      placeholder: "- Related #이슈번호"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 버그 현상
      placeholder: "어떤 상황에서 어떤 오류가 발생하는지 적어주세요."
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 해결을 위해 해볼 것들 (To-do)
      description: "문제를 해결하기 위해 확인해야 할 사항이나 작업 순서를 적어주세요."
      placeholder: |
        - [ ] 로그 확인 및 원인 분석
        - [ ] 로컬 환경에서 재현 테스트
        - [ ] 관련 로직 코드 수정
        - [ ] 테스트 코드 작성 및 검증