name: Task
description: 개발/테스트 단위 작업
title: "[TASK] "
labels: ["task"]
body:
  - type: input
    id: parent
    attributes:
      label: "관련된 Story/Epic"
      description: "상위 Story 또는 Epic 이슈 번호를 입력하세요 (Jira 연동)"
      placeholder: "- Related #이슈번호 (예: #2, #15) "
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 작업 내용
      placeholder: User 엔티티 구현
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Done 기준
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2